### ISSUE TITLE
not generating for only one batch

### ISSUE THREAD

**Issue by varnit02** [pranavkhurana/Time-table-scheduler#11]
the tool is not generating time table for only one batch

**Comment by pranavkhurana** [comment]
Hey @imvarnit1996, the time table scheduling algo is such that it eases manual work of maintaining consistency when designing time table for multiple batches(classes). For a single batch, a time table can easily be formulated by hands within no time and there arises no point of inconsistency. So this software was designed to work with at least two batches. (I should mention that in the readme).

Please close issue if this answers ur query
Thanks :)
