### ISSUE TITLE
help me with this 

### ISSUE THREAD

**Issue by maneesh22** [pranavkhurana/Time-table-scheduler#18]
i got some trouble while running this project i clone your repository and i also installed the eclipse ide enterprise edition and tomcat server then import the project to eclipse ide while running it shows this
Screenshot (187)
Screenshot (188)while running it shows this

Screenshot (189)
Screenshot (177)
Screenshot (178)
Screenshot (180)
Screenshot (181)
Screenshot (182)
Screenshot (183)
Screenshot (184)
Screenshot (185)
Screenshot (186)

**Comment by maneesh22** [comment]
i have done it myself tq

**Comment by MEPRAKHAR** [comment]
were you getting error 404? if yes can you help me with it pls?
