### ISSUE TITLE
Multiple subjects for a teacher

### ISSUE THREAD

**Issue by rahulpateel** [pranavkhurana/Time-table-scheduler#3]
can we add multiple subjects for a teacher?
i am trying to add multiple subjects for a teacher
as follows
O.N.Singh AP-1101
O.N.Singh AM-1101

but i get wrong results
Please help me
Thank You

**Comment by pranavkhurana** [comment]
Doing this way would make the algo think of it as two different teachers and thus it may give wrong results.
Actually it does not currently take into account 'multiple subjects for a teacher' but you should be able to do it with a little tweak. I would appreciate your contribution.
PS: Sorry for the late response

**Comment by rahulpateel** [comment]
Thank you
