### ISSUE TITLE
I am not able give the inputs as I want 

### ISSUE THREAD

**Issue by akshayputtaswmay** [pranavkhurana/Time-table-scheduler#4]
When I run the project ,and enter the he details into the text fields I get one r the other error ,but it's working fine with the input .TXT file given in repo

**Comment by akshayputtaswmay** [comment]
So please can u help me to come out of it

**Comment by pranavkhurana** [comment]
Please specify what errors are you facing.

**Comment by priyankashinolikar** [comment]
Can you specify which jar files to add for deployment?

**Comment by pranavkhurana** [comment]
Since you(priyankashinolikar) have created another issue, I'll assume its safe to close this one.
